export const quotes = [
  'Aller mon pote !',
  'On se motive ;)',
  'Tu sais que tu déchires ?',
  'Pas comme çaaa !',
  "Il n'y a pas de réussite sans défaite.",
  "Choisissez de vous réveiller avec une attitude positive.",
  "La persévérance est la clé du succès.",
  "Il n'y a pas de limite à ce que vous pouvez accomplir.",
  "Soyez fier de vos réalisations, même les plus petites.",
  "Croyez en vous et tout deviendra possible.",
  "N'abandonnez jamais vos rêves.",
  "La vie est trop courte pour ne pas prendre des risques.",
  "La détermination est la clé de la réussite.",
  "Il n'y a pas de fin à l'apprentissage.",
  "Chaque échec est une opportunité de grandir.",
  "Il n'y a pas de succès sans effort.",
  "Il n'y a pas de limite à ce que vous pouvez devenir.",
  "Chaque jour est un nouveau départ.",
  "Il n'y a pas de succès sans persévérance.",
  "Il n'y a pas de réussite sans travail acharné.",
  "Il n'y a pas de fin à l'amélioration.",
  "Il n'y a pas de fin à la croissance personnelle."
]
